spring:
  datasource:
    url: jdbc:postgresql://172.21.148.217:5432/postgres
    username : postgres
    password : postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      show-sql: true
