spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username : postgres
    password : postgres

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      ddl-auto: update
      format_sql: true
      show-sql: true
